window.PDF_TOOLS=[
['jpg-to-pdf','JPG to PDF','Turn JPG images into a PDF','image-to-pdf','jpg image convert'],['png-to-pdf','PNG to PDF','Turn PNG images into a PDF','image-to-pdf','png image convert'],['webp-to-pdf','WEBP to PDF','Turn WEBP images into a PDF','image-to-pdf','webp image convert'],['bmp-to-pdf','BMP to PDF','Turn BMP images into a PDF','image-to-pdf','bmp image convert'],['tiff-to-pdf','TIFF to PDF','Turn TIFF images into a PDF','image-to-pdf','tiff image convert'],['html-to-pdf','HTML to PDF','Print HTML content to PDF','html-to-pdf','html convert'],['text-to-pdf','Text to PDF','Create a PDF from plain text','text-to-pdf','text convert'],['pdf-to-jpg','PDF to JPG','Export PDF pages as JPG images','pdf-to-image','jpg image convert'],['pdf-to-png','PDF to PNG','Export PDF pages as PNG images','pdf-to-image','png image convert'],['pdf-to-webp','PDF to WEBP','Export PDF pages as WEBP images','pdf-to-image','webp image convert'],['pdf-to-text','PDF to Text','Extract selectable text from a PDF','pdf-to-text','text extract'],['pdf-to-html','PDF to HTML','Export PDF text as semantic HTML','pdf-to-html','html extract'],
['merge-pdf','Merge PDF','Combine multiple PDF files in order','merge','combine join'],['split-pdf','Split PDF','Split a PDF into page files','split','separate pages'],['extract-pdf-pages','Extract PDF Pages','Save selected pages as a new PDF','select-pages','extract'],['delete-pdf-pages','Delete PDF Pages','Remove selected pages from a PDF','delete-pages','remove'],['rotate-pdf','Rotate PDF','Rotate every page in your PDF','rotate','orientation'],['reorder-pdf-pages','Reorder PDF Pages','Rearrange pages using a page order','reorder','organize'],['duplicate-pdf-pages','Duplicate PDF Pages','Copy selected pages in a PDF','duplicate','copy'],
['compress-pdf','Compress PDF','Create a smaller, optimized PDF copy','compress','size reduce'],['optimize-pdf','Optimize PDF','Save a clean browser-optimized PDF','optimize','size'],['flatten-pdf','Flatten PDF','Flatten form appearances where supported','flatten','forms'],
['edit-pdf','Edit PDF','Add text annotations to a PDF','add-text','edit'],['add-text-to-pdf','Add Text to PDF','Place text onto PDF pages','add-text','edit'],['add-image-to-pdf','Add Image to PDF','Place an image on the first PDF page','add-image','edit'],['add-shapes-to-pdf','Add Shapes to PDF','Add a rectangle shape to a PDF','shape','edit'],['draw-on-pdf','Draw on PDF','Draw a line on the first PDF page','draw','edit'],['highlight-pdf','Highlight PDF','Add a highlighted area to a PDF','highlight','edit'],['add-watermark','Add Watermark','Add a text watermark to every page','watermark','edit'],['remove-watermark','Remove Watermark','Attempt removal by redacting a selected area','remove-watermark','edit limitation'],['crop-pdf','Crop PDF','Crop every page to a custom margin','crop','edit'],['resize-pdf-pages','Resize PDF Pages','Resize pages to A4 or Letter','resize','edit'],
['protect-pdf','Protect PDF with Password','Set permissions and password protection','protect','password security limitation'],['unlock-pdf','Unlock PDF','Open a PDF you are authorized to access','unlock','password security limitation'],['remove-pdf-password','Remove PDF Password','Remove a password from an authorized file','unlock','password security limitation'],['encrypt-pdf','Encrypt PDF','Password encryption is not supported by pdf-lib','protect','password security limitation'],['decrypt-pdf','Decrypt PDF','Decrypt an authorized PDF when supported','unlock','password security limitation'],
['pdf-metadata-viewer','PDF Metadata Viewer','Read document metadata locally','metadata-view','information'],['edit-pdf-metadata','Edit PDF Metadata','Change title, author and subject','metadata-edit','information'],['pdf-page-counter','PDF Page Counter','Count pages in a PDF','page-count','information'],['pdf-file-size-checker','PDF File Size Checker','Check the size of a PDF file','size-check','information'],['pdf-information-viewer','PDF Information Viewer','View pages, size and metadata','info','information'],
['sign-pdf','Sign PDF','Place a typed signature in your PDF','signature','sign'],['add-signature','Add Signature','Add a typed signature to a PDF','signature','sign'],['add-page-numbers','Add Page Numbers','Number every page in a PDF','page-numbers','utility'],['add-header-footer','Add Header & Footer','Add text at page tops and bottoms','header-footer','utility'],['create-pdf-from-images','Create PDF from Images','Create a PDF from multiple images','image-to-pdf','utility'],['create-pdf-from-text','Create PDF from Text','Create a PDF from plain text','text-to-pdf','utility'],['compare-pdf-files','Compare PDF files','Compare extracted text from two PDFs','compare','utility'],['repair-pdf','Repair PDF','Try loading and saving a clean PDF copy','repair','utility limitation']
].map(([slug,name,description,type,keywords])=>({slug,name,description,type,keywords}));
